name: my-Firstworkflow
on: push
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Running single command in Job1
        run: echo "My first command in git action"
      - name: Checking the OS Release for gitHub
        run: cat /etc/os-release
      - name: calling sleep
        run: sleep 20
  job2:
    name: JOB2
    runs-on: ubuntu-latest
    steps:
      - name: Checking the host name for Runner
        run: hostname
      - name: Running the multiple commands
        run: |
            echo "Hi from tester"
            echo " current time is `date` "
            sleep 20
  job3:
    name: JOb3
    needs : job1
    runs-on: ubuntu-latest
    steps:
      - name: Job with single dependency
        run: sleep 10
  job4:
    name : JOB4
    needs : [job1, job2, job3]
    runs-on: ubuntu-latest
    steps:
      - name: Job with single dependency
        run: sleep 10      
